name: Azure Pages CI/CD

on:
  push:
    branches:
    - joslin
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - joslin

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v1
    - name: Build And Deploy
      id: builddeploy
      uses: 
      with:
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN_NICE_GROUND_08FA64CF }}
        action: 'upload'
        app_artifact_location: 'app' # App Content Path
        api_artifact_location: 'api' # Api Content Path - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: 
      with:
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN_NICE_GROUND_08FA64CF }}
        action: 'close'
